# name: General Pipeline
# on:
#   push:
#     paths-ignore:
#       - '*.md'
#       - 'docs/**'

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Running tests because non-documentation files were changed."
