name: Reusable Build and Test
on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '18'
      run_tests:
        required: false
        type: boolean
        default: true
    outputs:
      test_result:
        description: "Result of the tests"
        value: ${{ jobs.build-test.outputs.result }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set_result.outputs.test_result }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          
      - run: npm install
      
      - run: npm run test
        if: ${{ inputs.run_tests }}
        
      - id: set_result
        run: echo "test_result=passed" >> $GITHUB_OUTPUT

