# name: Scheduled Health Check
# on:
#   schedule:
#     - cron: '30 2 * * 1'
#   workflow_dispatch:

# jobs:
#   health-check:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Ping Website
#         run: |
#           HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" https://github.com)
#           echo "GitHub returned status code: $HTTP_STATUS"
#           if [ "$HTTP_STATUS" -ne 200 ] && [ "$HTTP_STATUS" -ne 301 ]; then
#             exit 1
#           fi
