name: Task 1 & 2 - Secrets
on: [push]
jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Try to print the secret directly
        run: echo "The secret is ${{ secrets.MY_SECRET_MESSAGE }}"
      - name: Use secret securely via Environment Variable
        env:
          SECURE_VAR: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          if [ -n "$SECURE_VAR" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is missing!"
          fi

