name: Task 6 - Caching
on: [push]

jobs:
  test-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Python pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-test
          
      - name: Install a huge package (TensorFlow)
        run: pip install tensorflow

